game:
  pre-game-spawn-x: 100
  pre-game-spawn-y: 100
  pre-game-spawn-z: 100
  world: "World"
  max-players: 6
  starting-message: "&1Game is now starting!"
  teleport-message: "&4Teleporting players to start location"
  start-loc-x: 0
  start-loc-y: 0
  start-loc-z: 0
  zombie-spawn-loc-x: 0
  zombie-spawn-loc-y: 0
  zombie-spawn-loc-z: 0
  skeleton-spawn-loc-x: 0
  skeleton-spawn-loc-y: 0
  skeleton-spawn-loc-z: 0
  required-points: 500
  banker-name: "&b&lBanker!"
  mob-repsawn-time: 10.5L
  mob-count: 3
